name: 'Build pkgdown site'
description: 'Builds a pkgdown site from the source files of the package at package_root'
inputs:
  package_root:
    description: 'The root directory of the source tree of the BioCro package relative to the GitHub workspace directory'
    default: '.'
  base_url:
    description: 'The URL of the site where the pkgdown documentation will be hosted.'
    default: ''
runs:
  using: "composite"
  steps:

    - name: Test for Pandoc
      id: pandoc-test
      run: pandoc --version
      shell: bash
      continue-on-error: true

    - name: Install Pandoc
      if: steps.pandoc-test.outcome == 'failure'
      uses: r-lib/actions/setup-pandoc@v2

    - name: Install TinyTex
      run: |
        install.packages('tinytex')
        tinytex::install_tinytex()

        # (tinytex::pdflatex, which is called by the
        # pdf_vignette_index.Rmd vignette, will automatically install
        # any additional needed LaTeX packages needed by the Rnw
        # vignettes.)

      shell: Rscript {0}

    - name: Copy and modify custom configuration file to override defaults
      run: |
        cp ./.github/actions/build_pkgdown_site/_pkgdown.yml .
        if [[ '${{ inputs.base_url }}' != '' ]]
        then
            echo "url: ${{ inputs.base_url }}" >> _pkgdown.yml
        fi
      shell: bash

    - name: Run pkgdown
      working-directory: ${{ inputs.package_root }}/documentation/script
      run: |
        ./run_pkgdown.sh
      shell: bash
