name: 'Render Bookdown Book'
description: 'Builds the Bookdown developer documentation, installing any needed prerequisites'
inputs:
  package_root:
    description: 'The root directory of the source tree of the BioCro package relative to the GitHub workspace directory'
    default: '.'
runs:
  using: "composite"
  steps:
    - name: Test for Pandoc
      id: pandoc-test
      run: pandoc --version
      shell: bash
      continue-on-error: true

    - name: Install Pandoc
      if: steps.pandoc-test.outcome == 'failure'
      uses: r-lib/actions/setup-pandoc@v2

    - name: 8. Install bookdown
      run: |
        install.packages(c("bookdown"))
      shell: Rscript {0}

    - name: 9. Run bookdown
      working-directory: ${{ inputs.package_root }}/documentation/script
      run: |
        REFERENCE_ONLINE_BIOCRO_FILES=TRUE Rscript run_bookdown.R
      shell: bash
