name: Automatically generate documentation


on:
  push:
    branches:
      - master

    tags:
      - '*'

  # This event creates an artifact for download but does not write to
  # the BioCro documentation repository:
  pull_request:


jobs:

  call-generate-documentation:
    uses: ./.github/workflows/document.yml
    with:
      publish: ${{ github.event_name != 'pull_request' }}